FROM arm64v8/ubuntu:16.04
MAINTAINER Feisal Lam-Lion <feisal@lamlion.com>

ENV T_LANG nld
# Set the locale
RUN apt-get clean && apt-get update && apt-get install -y locales
RUN locale-gen en_US.UTF-8  
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  


RUN apt-get update && apt-get install -y \
	tesseract-ocr \
	tesseract-ocr-${T_LANG} \
	ghostscript \
	imagemagick \
	python \
	python-pip \
	python-dev \
	gcc \
	libjpeg-dev \
	minizip \
	poppler-utils \ 
	libtiff5-dev \
	libjpeg8-dev \
	zlib1g-dev \
	libfreetype6-dev \
 	liblcms2-dev \
	libwebp-dev \
	tcl8.5-dev \
	tk8.5-dev \
	python-tk

RUN pip install pypdfocr
RUN cp /usr/share/tesseract-ocr/tessdata/${T_LANG}.traineddata /usr/share/tesseract-ocr/tessdata/osd.traineddata

# Patch for Issue #41 of pypdfocr 0.9.0 - to be fixed in 0.9.1
WORKDIR /
# COPY issue_41.patch .
# RUN patch -l /usr/local/lib/python2.7/dist-packages/pypdfocr/pypdfocr_watcher.py -i issue_41.patch

VOLUME /media

ENTRYPOINT ["/usr/local/bin/pypdfocr"]
